definitions:
  system.Response:
    properties:
      status:
        type: string
    type: object
  users.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  users.Response:
    properties:
      status:
        type: string
    type: object
  users.UserRequestModel:
    properties:
      custom_id:
        type: string
      email:
        type: string
      external_email:
        type: string
      id:
        type: string
      is_enable:
        type: boolean
      name:
        type: string
      password_hash:
        type: string
      period:
        type: string
    type: object
  users.UserResponseModel:
    properties:
      custom_id:
        type: string
      email:
        type: string
      external_email:
        type: string
      id:
        type: string
      is_enable:
        type: boolean
      name:
        type: string
      period:
        type: string
    type: object
  users.UsersResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/users.UserResponseModel'
        type: array
      pages:
        type: integer
      total_count:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: ユーザー管理サービスAPIの機能
  title: ユーザー管理サービスAPI
  version: v0.1.0
paths:
  /v1/health:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/system.Response'
      summary: 死活監視用
      tags:
      - healthcheck
  /v1/users:
    get:
      consumes:
      - application/json
      description: ユーザーのメールアドレスやカスタムIDで検索
      parameters:
      - description: メールアドレス
        in: query
        name: email
        type: string
      - description: カスタムID
        in: query
        name: custom_id
        type: string
      - description: 名前
        in: query
        name: name
        type: string
      - description: 外部メールアドレス
        in: query
        name: external_email
        type: string
      - description: 期間
        in: query
        name: period
        type: string
      - description: 有効フラグ
        in: query
        name: is_enable
        type: boolean
      - description: 取得件数
        in: query
        name: limit
        type: string
      - description: ページ番号
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.UsersResponse'
      summary: ユーザー検索
      tags:
      - Users
    patch:
      consumes:
      - application/json
      parameters:
      - description: ユーザー情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/users.UserRequestModel'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/users.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/users.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/users.ErrorResponse'
      summary: ユーザー情報を部分更新
      tags:
      - Users
    post:
      consumes:
      - application/json
      parameters:
      - description: ユーザー情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/users.UserRequestModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/users.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/users.ErrorResponse'
      summary: ユーザー情報を登録
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: ユーザー情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/users.UserRequestModel'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/users.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/users.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/users.ErrorResponse'
      summary: ユーザー情報を更新(置き換え)
      tags:
      - Users
  /v1/users/:id:
    get:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: path
        name: request
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.UserResponseModel'
      summary: ユーザーの詳細情報を取得
      tags:
      - Users
  /v1/users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/users.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/users.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/users.ErrorResponse'
      summary: ユーザーを削除
      tags:
      - Users
swagger: "2.0"
