definitions:
  api_internal_controller_system.Response:
    properties:
      status:
        type: string
    type: object
  api_internal_controller_users.UserResponseModel:
    properties:
      custom_id:
        type: string
      email:
        type: string
      external_email:
        type: string
      id:
        type: string
      is_enable:
        type: boolean
      name:
        type: string
      period:
        type: string
    type: object
  api_internal_controller_users.UsersResponse:
    properties:
      pages:
        type: integer
      total_count:
        type: integer
      users:
        items:
          $ref: '#/definitions/api_internal_controller_users.UserResponseModel'
        type: array
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_system.Response:
    properties:
      status:
        type: string
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_users.UserResponseModel:
    properties:
      custom_id:
        type: string
      email:
        type: string
      external_email:
        type: string
      id:
        type: string
      is_enable:
        type: boolean
      name:
        type: string
      period:
        type: string
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_users.UsersResponse:
    properties:
      pages:
        type: integer
      total_count:
        type: integer
      users:
        items:
          $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_users.UserResponseModel'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: ユーザー管理サービスAPIの機能
  title: ユーザー管理サービスAPI
  version: v0.1.0
paths:
  /v1/health:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_internal_controller_system.Response'
      summary: 死活監視用
      tags:
      - healthcheck
  /v1/users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_internal_controller_users.UsersResponse'
      summary: ユーザー一覧取得
      tags:
      - users
  /v1/users/:id:
    get:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: path
        name: request
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_internal_controller_users.UserResponseModel'
      summary: ユーザーの詳細情報を取得
      tags:
      - Users
swagger: "2.0"
