definitions:
  api_internal_controller_roles.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  api_internal_controller_roles.Response:
    properties:
      status:
        type: string
    type: object
  api_internal_controller_roles.RoleRequestModel:
    properties:
      custom_id:
        type: string
      id:
        type: string
      is_enable:
        type: boolean
      name:
        type: string
      permission:
        items:
          type: string
        type: array
    type: object
  api_internal_controller_roles.RoleResponseModel:
    properties:
      created_at:
        type: string
      custom_id:
        type: string
      id:
        type: string
      is_enable:
        type: boolean
      is_system:
        type: boolean
      name:
        type: string
      permission:
        type: integer
      updated_at:
        type: string
    type: object
  api_internal_controller_roles.RolesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/api_internal_controller_roles.RoleResponseModel'
        type: array
      pages:
        type: integer
      total_count:
        type: integer
    type: object
  api_internal_controller_system.Response:
    properties:
      status:
        type: string
    type: object
  api_internal_controller_users.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  api_internal_controller_users.Response:
    properties:
      status:
        type: string
    type: object
  api_internal_controller_users.UserRequestModel:
    properties:
      custom_id:
        type: string
      email:
        type: string
      external_email:
        type: string
      id:
        type: string
      is_enable:
        type: boolean
      joined_at:
        type: string
      name:
        type: string
      password_hash:
        type: string
      period:
        type: string
    type: object
  api_internal_controller_users.UserResponseModel:
    properties:
      created_at:
        type: string
      custom_id:
        type: string
      email:
        type: string
      external_email:
        type: string
      id:
        type: string
      is_enable:
        type: boolean
      joined_at:
        type: string
      name:
        type: string
      period:
        type: string
      updated_at:
        type: string
    type: object
  api_internal_controller_users.UsersResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/api_internal_controller_users.UserResponseModel'
        type: array
      pages:
        type: integer
      total_count:
        type: integer
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.Response:
    properties:
      status:
        type: string
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.RoleRequestModel:
    properties:
      custom_id:
        type: string
      id:
        type: string
      is_enable:
        type: boolean
      name:
        type: string
      permission:
        items:
          type: string
        type: array
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.RoleResponseModel:
    properties:
      created_at:
        type: string
      custom_id:
        type: string
      id:
        type: string
      is_enable:
        type: boolean
      is_system:
        type: boolean
      name:
        type: string
      permission:
        type: integer
      updated_at:
        type: string
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.RolesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.RoleResponseModel'
        type: array
      pages:
        type: integer
      total_count:
        type: integer
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_system.Response:
    properties:
      status:
        type: string
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_users.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_users.Response:
    properties:
      status:
        type: string
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_users.UserRequestModel:
    properties:
      custom_id:
        type: string
      email:
        type: string
      external_email:
        type: string
      id:
        type: string
      is_enable:
        type: boolean
      joined_at:
        type: string
      name:
        type: string
      password_hash:
        type: string
      period:
        type: string
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_users.UserResponseModel:
    properties:
      created_at:
        type: string
      custom_id:
        type: string
      email:
        type: string
      external_email:
        type: string
      id:
        type: string
      is_enable:
        type: boolean
      joined_at:
        type: string
      name:
        type: string
      period:
        type: string
      updated_at:
        type: string
    type: object
  github.com_UniPro-tech_UniQUE-API_api_internal_controller_users.UsersResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_users.UserResponseModel'
        type: array
      pages:
        type: integer
      total_count:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: ユーザー管理サービスAPIの機能
  title: ユーザー管理サービスAPI
  version: v0.1.0
paths:
  /v1/health:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_internal_controller_system.Response'
      summary: 死活監視用
      tags:
      - healthcheck
  /v1/roles:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.RolesResponse'
      summary: ロール一覧取得
      tags:
      - Roles
    patch:
      consumes:
      - application/json
      parameters:
      - description: ロール情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.RoleRequestModel'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.ErrorResponse'
      summary: ロール情報を部分更新
      tags:
      - Roles
    post:
      consumes:
      - application/json
      parameters:
      - description: ロール情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.RoleRequestModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.ErrorResponse'
      summary: ロール情報を登録
      tags:
      - Roles
  /v1/roles/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ロールID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.ErrorResponse'
      summary: ロールを削除
      tags:
      - Roles
    put:
      consumes:
      - application/json
      parameters:
      - description: ロール情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.RoleRequestModel'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_UniPro-tech_UniQUE-API_api_internal_controller_roles.ErrorResponse'
      summary: ロール情報を更新(置き換え)
      tags:
      - Roles
  /v1/users:
    get:
      consumes:
      - application/json
      description: ユーザーのメールアドレスやカスタムIDで検索
      parameters:
      - description: メールアドレス
        in: query
        name: email
        type: string
      - description: カスタムID
        in: query
        name: custom_id
        type: string
      - description: 名前
        in: query
        name: name
        type: string
      - description: 外部メールアドレス
        in: query
        name: external_email
        type: string
      - description: 期間
        in: query
        name: period
        type: string
      - description: 有効フラグ
        in: query
        name: is_enable
        type: boolean
      - description: 取得件数
        in: query
        name: limit
        type: string
      - description: ページ番号
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_internal_controller_users.UsersResponse'
      summary: ユーザー検索
      tags:
      - Users
    patch:
      consumes:
      - application/json
      parameters:
      - description: ユーザー情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api_internal_controller_users.UserRequestModel'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_internal_controller_users.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api_internal_controller_users.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api_internal_controller_users.ErrorResponse'
      summary: ユーザー情報を部分更新
      tags:
      - Users
    post:
      consumes:
      - application/json
      parameters:
      - description: ユーザー情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api_internal_controller_users.UserRequestModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_internal_controller_users.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_internal_controller_users.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api_internal_controller_users.ErrorResponse'
      summary: ユーザー情報を登録
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: ユーザー情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api_internal_controller_users.UserRequestModel'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_internal_controller_users.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api_internal_controller_users.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api_internal_controller_users.ErrorResponse'
      summary: ユーザー情報を更新(置き換え)
      tags:
      - Users
  /v1/users/:id:
    get:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: path
        name: request
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_internal_controller_users.UserResponseModel'
      summary: ユーザーの詳細情報を取得
      tags:
      - Users
  /v1/users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api_internal_controller_users.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api_internal_controller_users.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api_internal_controller_users.ErrorResponse'
      summary: ユーザーを削除
      tags:
      - Users
swagger: "2.0"
